inherit_from:
  - minimal.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - "vendor/**/*"
    - "**/*_pb.rb"

## Metrics
Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "**/spec/**/*.rb"
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

## Lint
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

## RSpec
RSpec/NamedSubject:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
